apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-portal
  labels:
    app: main-portal
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
  selector:
    matchLabels:
      app: main-portal
  template:
    metadata:
      labels:
        app: main-portal
    spec:
      containers:
      - name: main-portal
        image: frogcloud/tomcat8-jre8-ubuntu20.04:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: main-portal-svc
spec:
    ports:
    - name: web-port
      port: 8080
      targetPort: 8080
    selector:
      app: main-portal
    type: ClusterIP
